const categories =
  { music:
     [ 'a capella',
       'acoustic',
       'alt rock',
       'bluegrass',
       'blues',
       'choral',
       'classical',
       'concert',
       'country',
       'dance club',
       'electronic',
       'folk',
       'funk',
       'heavy metal',
       'hip hop',
       'jazz',
       'karaoke',
       'latin',
       'live music',
       'marching band',
       'opera',
       'punk',
       'r&b & soul',
       'reggae',
       'religious',
       'rock',
       'rockabilly' ],
    'performing arts':
     [ 'auditions',
       'comedy',
       'dance',
       'improv',
       'magic show',
       'open mic',
       'theatre',
       'variety show' ],
    'visual arts':
     [ 'architecture',
       'drawing & painting',
       'film',
       'galleries',
       'glass art',
       'media arts',
       'photography',
       'sculpture' ],
    'literary arts':
     [ 'books',
       'poetry',
       'reading',
       'storytelling',
       'writing' ],
    'sports & outdoors':
     [ 'fitness',
       'organized sport',
       'outdoor recreation',
       'races',
       'running' ],
    'hobbies & interests':
     [ 'automotive',
       'collectibles',
       'crafts',
       'farming & ranching',
       'fashion',
       'games',
       'home & garden',
       'markets & shopping',
       'other interests',
       'travel' ],
    'food & drink':
     [ 'beer',
       'coffee & tea',
       'culinary arts',
       'drinks',
       'food',
       'food trucks',
       'wine' ],
    lifestyle:
     [ 'culture & ethnic',
       'health & wellness',
       'parenting',
       'personal finance',
       'pets',
       'relationships',
       'religion & spirituality' ],
    education:
     [ 'animals & zoos',
       'conferences & workshops',
       'lessons & classes',
       'museums & exhibits',
       'sightseeing',
       'special attractions',
       'talks & lectures',
       'webinar' ],
    professional:
     [ 'business',
       'career & jobs',
       'law',
       'medicine',
       'networking',
       'real estate',
       'schools',
       'science',
       'technology' ],
    community:
     [ 'LGBT',
       'causes & activism',
       'community groups',
       'family',
       'fundraisers',
       'kids',
       'parks & gardens',
       'patriotic',
       'politics & government',
       'seniors',
       'singles',
       'teens',
       'volunteer',
       'women' ],
    'special events':
     [ 'awards ceremony',
       'farmers markets',
       'festivals & fairs',
       'flea markets',
       'holidays',
       'parties & reunions',
       'tradeshows & expos',
       'yard sales' ]
  };

export default categories;
